// web-react/src/views/FlaskLogin.tsx
import 'bootstrap/dist/css/bootstrap.min.css';

import {useEffect} from 'react';
import {useState} from 'react';
import {useSelector, useDispatch} from 'react-redux';
import {mapStateToProps, mapDispatchToProps} from '../store/reducer';
import {connect} from 'react-redux';

import {Navbar} from 'react-bootstrap';
import {Form, Button} from 'react-bootstrap';
import {Container, Row, Col} from 'react-bootstrap';

import {useNavigate} from "react-router-dom";
import axios from 'axios';

var styles = {
  margin: {
    margin: "55pt 10pt 10pt 10pt",
  },
  white: {
    color: "white",
  }
};

function FlaskLogin() {
  const [userName, setUserName] = useState('');
  const [password, setPassword] = useState('');
  const [message, setMessage] = useState('');
  const navigate = useNavigate();
  const sessionId = useSelector((state: {sessionId: string}) => state.sessionId);
  const dispatch = useDispatch();
  useEffect(() => {
    if (sessionId !== '') {
      dispatch({type: 'UPDATE', payload: ''});
      const formData = new FormData();
      axios.post('/unauth', formData);
    }
  }, []);  
  const login = async () => {
    if (! userName) {
      setMessage('User Name is required.');
      return	
    }
    if (! password) {
      setMessage('Password is required.');
      return
    }  
    const formData = new FormData();
    formData.append('user_name', userName);
    formData.append('password', password);
    await axios.post('/auth', formData)
    .then (function(response) {
      if (response.data.status === 'action-ok') {
        dispatch({type: 'UPDATE', payload: 'in session'});
        navigate('/FlaskHome');
        return;
      }
      else {
        setMessage(response.data.message);
        return;
      }
    })
    .catch (function(error) {
      setMessage('Network trouble has occurred.');
      return
    });
  };
  return (
    <>
      <header>
        <Navbar expand="lg" className="fixed-top navbar navbar-expand-lg px-lg-3 navbar-dark bg-primary">
          <Navbar.Brand><b>lab-flask</b></Navbar.Brand>
        </Navbar>
      </header>
      <footer className="footer fixed-bottom mt-auto p-lg-2 navbar-dark bg-primary">
        <span style={styles.white}>Copyright &copy; Xxxx Co., Ltd.</span>
      </footer>
      <main style={styles.margin}>
        <h5>Login</h5>
        <Container fluid="true">
          <Row noGutters="true">
            <Col>{message}</Col>
          </Row>
          <Row noGutters="true">
            <Col xs={12} md={4}>
              <Form.Control type="text" value={userName} placeholder="User Name" onChange={(e) => setUserName(e.target.value)} />
            </Col>
          </Row>
          <Row noGutters="true">
            <Col xs={12} md={4}>
              <Form.Control type="password" value={password} placeholder="Password" onChange={(e) => setPassword(e.target.value)} />
            </Col>
          </Row>
          <Row noGutters="true">
            <Col md="auto">
              <Button variant="outline-success" onClick={login}>Login</Button>
            </Col>
          </Row>
        </Container>
      </main>
    </>
  );
}

export default connect(mapStateToProps, mapDispatchToProps)(FlaskLogin);

// web-vue/src/views/FlaskLogin.vue
<template>
  <v-app>
    <v-app-bar color="blue" app dark>
      <v-toolbar-title><h3 class="display-1">lab-flask</h3></v-toolbar-title>
    </v-app-bar>
    <v-footer color="blue" app dark>Copyright &copy; Xxxx Co., Ltd.</v-footer>
    <v-main>
      <v-container fluid>
        <v-row no-gutters>
          <v-col><h3 class="display-1">Login</h3></v-col>
        </v-row>
        <v-row no-gutters>
          <v-col>{{ message }}</v-col>
        </v-row>
        <v-row>
          <v-col cols="4">
            <v-form>
              <v-text-field autocomplete="off" prepend-icon="mdi-account" clearable label="User Name" v-model="userName" />
              <v-text-field
                autocomplete="off" prepend-icon="mdi-lock" clearable label="Password" v-model="password"
                v-bind:type="showPassword ? 'text' : 'password'"
                v-bind:append-icon="showPassword ? 'mdi-eye' : 'mdi-eye-off'"
                @click:append="showPassword = ! showPassword" />
              <v-btn  variant="outlined" color="success" @click="login" style="text-transform: none">Login</v-btn>
            </v-form>
          </v-col>
        </v-row>
      </v-container>
    </v-main>
  </v-app>
</template>

<script setup>

import axios from 'axios'

import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { useStore } from '../stores/store'

const router = useRouter()
const store = useStore()

const message = ref('')
const showPassword = ref(false)
const userName = ref('')
const password = ref('')

if (store.sessionId != '') {
  const formData = new FormData()
  axios.post('/unauth', formData)
  store.sessionId = ''
}

function login() {
  if (! userName.value) {
    message.value = 'User Name is required.'
    return  
  }
  if (! password.value) {
    message.value = 'Password is required.'
    return
  }
  const formData = new FormData()
  formData.append('user_name', userName.value)
  formData.append('password', password.value)
  axios.post('/auth', formData)
  .then (function(response) {
    if (response.data.status == 'action-ok') {
      store.sessionId = "in session"
      router.push('/FlaskHome')
      return
    }
    else {
      message.value = response.data.message
      return
    }
  })
  .catch (function(error) {
    message.value = 'Network trouble has occurred.'
    return
  })
}

</script>
